# Generated by Django 3.1.4 on 2021-04-16 19:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_district_profile_township'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Sesotho', 'Sesotho'), ('Physics', 'Physics'), ('Chemistry', 'Chemisty'), ('Biology', 'Biology'), ('Geograpy', 'Geograpy'), ('Accounting', 'Accounting'), ('Commerce', 'Commerce'), ('French', 'French'), ('Coding', 'Coding'), ('Business-EDU', 'Business-EDU'), ('Career-guidance', 'Career-guidance'), ('Medicine', 'Medicine')], max_length=134, verbose_name='select your Subject(s)'),
        ),
    ]
