# Generated by Django 3.1.4 on 2021-04-16 19:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210416_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Sesotho', 'Sesotho'), ('Physics', 'Physics'), ('Chemistry', 'Chemisty'), ('Biology', 'Biology'), ('Geograpy', 'Geograpy'), ('Accounting', 'Accounting'), ('Commerce', 'Commerce'), ('French', 'French'), ('Computer Coding', 'Computer Coding'), ('Business-EDU', 'Business-EDU'), ('Career-guidance', 'Career-guidance'), ('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Psychology', 'Psychology'), ('Entrepreneurship', 'Entrepreneurship'), ('Pure Sciences', 'Pure Sciences'), ('Finance & Investment', 'Finance & Investment'), ('Technical skills', 'Technical skills'), ('Farming', 'Farming'), ('Arts & Media', 'Arts & Media'), ('Leadership Skills', 'Leadership Skills')], max_length=274, verbose_name='select your Subject(s)'),
        ),
    ]
