# Generated by Django 3.1.4 on 2021-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210416_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher/Tutor', 'Teacher/Tutor'), ('Mentor', 'Mentor')], max_length=100, verbose_name='select your group'),
        ),
    ]
