# Generated by Django 3.1.4 on 2021-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210416_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, max_length=300, verbose_name='school/institute'),
        ),
    ]
