# Generated by Django 3.1.4 on 2021-10-13 08:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210614_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Student', 'Student'), ('Teacher/Tutor', 'Teacher/Tutor'), ('Mentor', 'Mentor'), ('Mentee', 'Mentee')], max_length=100, verbose_name='select your group'),
        ),
    ]
