# Generated by Django 3.1.4 on 2021-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211013_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher/Tutor', 'Teacher/Tutor'), ('Mentor', 'Mentor'), ('Mentee', 'Mentee')], max_length=100, verbose_name='select your group'),
        ),
    ]
