# Generated by Django 3.1.4 on 2021-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211013_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=models.CharField(choices=[('Student/Mentee', 'Student/Mentee'), ('Teacher/Tutor', 'Teacher/Tutor'), ('Mentor', 'Mentor'), ('Mentor&Teacher', 'Mentor&Teacher'), ('Student&Mentor', 'Student&Mentor'), ('Mentor&Mentee', 'Mentor&Mentee')], max_length=100, verbose_name='select your group'),
        ),
    ]
