# Generated by Django 3.1.4 on 2022-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211013_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=models.CharField(choices=[('Student/Mentee', 'Student/Mentee'), ('Mentor', 'Mentor'), ('Mentor&Teacher', 'Mentor&Teacher'), ('Student&Mentor', 'Student&Mentor'), ('Mentor&Mentee', 'Mentor&Mentee')], max_length=100, verbose_name='select your group'),
        ),
    ]
