# Generated by Django 3.1.4 on 2021-04-19 19:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210419_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
