# Generated by Django 3.1.4 on 2021-04-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='content',
        ),
    ]
