# Generated by Django 3.1.4 on 2021-04-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210419_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='reply',
        ),
    ]
