# Generated by Django 3.1.4 on 2021-04-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210420_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
