# Generated by Django 3.1.4 on 2021-05-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_comment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
