# Generated by Django 3.1.4 on 2021-05-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
