# Generated by Django 3.1.4 on 2021-05-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_delete_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
