# Generated by Django 3.1.4 on 2021-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hash')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Hash',
                'verbose_name_plural': 'Hashes',
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='hashes',
            field=models.ManyToManyField(related_name='hashes', to='feed.Hash'),
        ),
    ]
