# Generated by Django 3.1.4 on 2021-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_delete_like'),
        ('feed', '0002_auto_20210512_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='hashes',
        ),
        migrations.AddField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(related_name='hashes', to='blog.Tag'),
        ),
        migrations.DeleteModel(
            name='Hash',
        ),
    ]
