# Generated by Django 3.1.4 on 2021-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210521_1115'),
        ('feed', '0008_auto_20210525_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='hashes', to='blog.Tag'),
        ),
    ]
