# Generated by Django 3.1.4 on 2021-06-16 10:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210525_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
