# Generated by Django 3.1.4 on 2021-05-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210517_1323'),
        ('notifications', '0005_auto_20210517_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_post',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_feed', to='feed.feed'),
        ),
        migrations.AlterField(
            model_name='notification_feed',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='random', to='feed.feed'),
        ),
    ]
