# Generated by Django 3.1.4 on 2021-05-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210517_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification_feed',
        ),
    ]
